image: node:10.15
cache:
  key: project
  paths: 
  - node_modules/
stages:
  - build
before_script:
  - npm install
Pages:
  stage: build
  script: 
  - npm run build
  artifacts:
    paths:
    - build
